### ISSUE TITLE
Overriding default cmake find modules?

### ISSUE THREAD

**Issue by benbennett** [leapmotion/cmake-modules#13]
I am trying to understand why you overriding many default cmake modules. I tried using your repo just for FindLeap but it broke my code using protocol buffers. 

Anyway you split the ones are used for compiling against leap and the custom ones in another directory? 
Or possible include just the FindLeap.cmake and dependencies as part of the release?

**Comment by codemercenary** [comment]
Good question.

The reason is that, when we released this repo, a lot of these finder modules were hopelessly broken.  Later releases of cmake have, in fact, corrected some of these problems--in particular, for instance, we needed OpenSSL's crypto and ssl libraries to be reported separately and this was only fixed in [CMake 3.2.2](http://www.cmake.org/cmake/help/v3.2/release/3.2.html) which was released 13-Apr-2015.

Your suggestion is a good one.  Releasing just `FindLeap.cmake` is likely the best solution here.  As an interim fix, feel free to copy `FindLeap.cmake` for your internal use, it's got a permissive license.

**Comment by benbennett** [comment]
I have copied it. I cleaned up the FindLeap https://github.com/benbennett/cmake-modules/tree/improved_findleap
Split the cmake module path to not override defaults. 
https://github.com/benbennett/cmake-modules/tree/cmake_split_module_dirs

**Comment by codemercenary** [comment]
Nice!  Would you mind submitting a pull request?
